language: go

go:
  - "1.9.x"
  - "1.10.x"
  - master

before_script:
  - go get -t ./...
  
script: 
  - go test -v . -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)